# Generated by Django 5.2.7 on 2025-11-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='OutfitRecommendation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('rec_1', models.TextField()),
                ('rec_2', models.TextField()),
                ('rec_3', models.TextField()),
                ('explanation', models.TextField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'outfit_recommendations',
            },
        ),
    ]
