# Generated by Django 5.2.7 on 2025-11-05 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommend', '0001_initial'),
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitrecommendation',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='outfit_recommendations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='outfitrecommendation',
            name='weather_data',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='outfit_recommendations',
                to='weather.weatherdata',
            ),
        ),
        migrations.AddIndex(
            model_name='outfitrecommendation',
            index=models.Index(
                fields=['user', '-created_at'], name='outfit_reco_user_id_5de9f1_idx'
            ),
        ),
    ]
