# Generated by Django 5.2.7 on 2025-11-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='작성 날짜')),
                (
                    'satisfaction',
                    models.IntegerField(
                        choices=[
                            (0, '😔 별로예요'),
                            (1, '😐 보통이에요'),
                            (2, '🙂 좋아요'),
                            (3, '😄 아주 좋아요'),
                        ],
                        default=1,
                        help_text='오늘의 기분 점수 (0~3)',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diary',
                'verbose_name_plural': 'Diaries',
                'db_table': 'diary',
            },
        ),
    ]
