# Generated by Django 5.2.7 on 2025-11-11 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='작성 날짜')),
                ('emotion', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='diary_images/%Y/%m/%d/',
                        verbose_name='첨부 이미지 파일',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'weather_data',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='weather.weatherdata',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Diary',
                'verbose_name_plural': 'Diaries',
                'db_table': 'diary',
                'ordering': ['-date', '-updated_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
