# Generated by Django 5.2.7 on 2025-11-05 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_initial'),
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='diaries',
                to=settings.AUTH_USER_MODEL,
                verbose_name='작성자',
            ),
        ),
        migrations.AddField(
            model_name='diary',
            name='weather_data',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='diaries',
                to='weather.weatherdata',
            ),
        ),
    ]
