# Generated by Django 5.2.7 on 2025-11-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='WeatherLocation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('dp_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'weather_location',
                'unique_together': {('city', 'district')},
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_time', models.DateTimeField()),
                ('valid_time', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('rain_probability', models.FloatField(blank=True, null=True)),
                ('rain_volume', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'location',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='weather_data',
                        to='weather.weatherlocation',
                    ),
                ),
            ],
            options={
                'db_table': 'weather_data',
                'ordering': ['-valid_time'],
                'indexes': [
                    models.Index(fields=['base_time'], name='idx_weather_base_time'),
                    models.Index(fields=['valid_time'], name='idx_weather_valid_time'),
                    models.Index(
                        fields=['location', '-valid_time'], name='idx_loc_valid_desc'
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('location', 'valid_time'),
                        name='uniq_location_valid_time',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('humidity__gte', 0), ('humidity__lte', 100)
                        ),
                        name='humidity_range_0_100',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('rain_probability__gte', 0.0),
                            ('rain_probability__lte', 100.0),
                        ),
                        name='rain_prob_range_0_100',
                    ),
                ],
            },
        ),
    ]
