# Generated by Django 5.2.7 on 2025-11-05 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritelocation',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='favorite_locations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='favoritelocation',
            index=models.Index(
                fields=['user', 'is_default'], name='favorite_lo_user_id_846446_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='favoritelocation',
            constraint=models.UniqueConstraint(
                condition=models.Q(('deleted_at__isnull', True)),
                fields=('user', 'city', 'district'),
                name='uq_favorite_user_city_district',
            ),
        ),
        migrations.AddConstraint(
            model_name='favoritelocation',
            constraint=models.UniqueConstraint(
                condition=models.Q(('deleted_at__isnull', True), ('is_default', True)),
                fields=('user',),
                name='uq_default_favorite_per_user',
            ),
        ),
    ]
