# Generated by Django 5.2.7 on 2025-11-06 01:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritelocation',
            options={'ordering': ['order']},
        ),
        migrations.RemoveConstraint(
            model_name='favoritelocation',
            name='uq_favorite_user_city_district',
        ),
        migrations.RemoveConstraint(
            model_name='favoritelocation',
            name='uq_default_favorite_per_user',
        ),
        migrations.RemoveIndex(
            model_name='favoritelocation',
            name='favorite_lo_user_id_846446_idx',
        ),
        migrations.RemoveField(
            model_name='favoritelocation',
            name='is_default',
        ),
        migrations.AddField(
            model_name='favoritelocation',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='favoritelocation',
            index=models.Index(
                fields=['user', 'order'], name='favorite_lo_user_id_b794bd_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='favoritelocation',
            constraint=models.UniqueConstraint(
                condition=models.Q(('deleted_at__isnull', True)),
                fields=('user', 'city', 'district'),
                name='uq_favorite_unique_location_per_user',
            ),
        ),
    ]
