# Generated by Django 5.2.7 on 2025-11-05 07:43

import apps.users.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'email',
                    models.EmailField(db_index=True, max_length=150, unique=True),
                ),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'nickname',
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    'phone',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='국가번호 포함 가능. 숫자, +, - 허용',
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='전화번호 형식이 올바르지 않습니다. (숫자, +, - 허용, 9~20자리)',
                                regex='^[0-9+\\-]{9,20}$',
                            )
                        ],
                    ),
                ),
                (
                    'gender',
                    models.CharField(
                        blank=True,
                        choices=[('Woman', '여성'), ('Man', '남성'), ('0', '기타')],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    'age_group',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('10', '10대'),
                            ('20', '20대'),
                            ('30', '30대'),
                            ('40', '40대'),
                            ('50', '50대'),
                            ('60+', '60대 이상'),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name='연령대',
                    ),
                ),
                ('email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=20)),
                ('provider_user_id', models.CharField(max_length=200)),
                (
                    'connected_at',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='social_accounts',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'db_table': 'social_accounts',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nickname'], name='users_nicknam_172a64_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('provider', 'provider_user_id')},
        ),
    ]
