# Generated by Django 5.2.7 on 2025-11-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_phone_af6883_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_regions',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="사용자가 등록한 즐겨찾는 지역 (최대 3가지, 예: ['서울','부산','대구'])",
                null=True,
            ),
        ),
    ]
