# Generated by Django 5.2.7 on 2025-11-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_users_phone_af6883_idx_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age_group',
            field=models.CharField(
                blank=True,
                choices=[
                    ('10', 'ten'),
                    ('20', 'twenty'),
                    ('30', 'thirty'),
                    ('40', 'fourty'),
                    ('50', 'fifth'),
                    ('60+', 'Other'),
                ],
                max_length=10,
                null=True,
                verbose_name='연령대',
            ),
        ),
    ]
