# Generated by Django 5.2.7 on 2025-11-10 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_age_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_jwt', models.CharField(max_length=500)),
                ('refresh_jwt', models.CharField(max_length=500)),
                ('access_expires_at', models.DateTimeField()),
                ('refresh_expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='token',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'tokens',
                'indexes': [
                    models.Index(
                        fields=['user', 'revoked'], name='tokens_user_id_0ce26e_idx'
                    ),
                    models.Index(
                        fields=['refresh_expires_at'], name='tokens_refresh_7da78a_idx'
                    ),
                ],
            },
        ),
    ]
