# Generated by Django 5.2.7 on 2025-11-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_auto_login',
            field=models.BooleanField(default=False),
        ),
    ]
