# Generated by Django 5.2.7 on 2025-11-17 05:02

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_token_is_auto_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='access_expires_at',
            field=models.DateTimeField(
                default=apps.users.models.default_access_expires
            ),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_expires_at',
            field=models.DateTimeField(
                default=apps.users.models.default_refresh_expires
            ),
        ),
    ]
