# Generated by Django 5.2.7 on 2025-11-11 15:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiModelSettings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=150, unique=True)),
                ('temperature_min', models.FloatField()),
                ('temperature_max', models.FloatField()),
                (
                    'humidity_min',
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    'humidity_max',
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    'weather_condition',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('', 'ANY'),
                            ('Clear', 'Clear'),
                            ('Clouds', 'Clouds'),
                            ('Rain', 'Rain'),
                            ('Snow', 'Snow'),
                            ('Drizzle', 'Drizzle'),
                            ('Thunderstorm', 'Thunderstorm'),
                            ('Mist', 'Mist'),
                            ('Fog', 'Fog'),
                            ('Haze', 'Haze'),
                            ('Smoke', 'Smoke'),
                            ('Dust', 'Dust'),
                            ('Squall', 'Squall'),
                            ('Tornado', 'Tornado'),
                        ],
                        max_length=100,
                    ),
                ),
                ('category_combo', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_model_settings',
                'indexes': [
                    models.Index(
                        fields=['active'], name='ai_model_se_active_6495a8_idx'
                    ),
                    models.Index(
                        fields=['weather_condition'],
                        name='ai_model_se_weather_efdc3f_idx',
                    ),
                    models.Index(
                        fields=['temperature_min', 'temperature_max'],
                        name='ai_model_se_tempera_f95ef2_idx',
                    ),
                    models.Index(
                        fields=['humidity_min', 'humidity_max'],
                        name='ai_model_se_humidit_94a017_idx',
                    ),
                ],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            ('temperature_min__lte', models.F('temperature_max'))
                        ),
                        name='chk_temp_min_le_max',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('humidity_min__gte', 0),
                            ('humidity_min__lte', 100),
                            ('humidity_max__gte', 0),
                            ('humidity_max__lte', 100),
                            ('humidity_min__lte', models.F('humidity_max')),
                        ),
                        name='chk_humidity_range_0_100',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='AiChatLogs',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('user_question', models.TextField()),
                ('ai_answer', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ai_chat_logs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'AiModelSettings',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='logs',
                        to='chat.aimodelsettings',
                    ),
                ),
            ],
            options={
                'db_table': 'ai_chat_logs',
                'indexes': [
                    models.Index(
                        fields=['user', 'session_id', '-created_at'],
                        name='ai_chat_log_user_id_0d2ea6_idx',
                    )
                ],
            },
        ),
    ]
